weights = 
{"valse_lente":
  {
    "time_signature": 0,
    "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0, // apocalyptica
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.05, //lana del rey 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
    
    
    
    
    
   
},
"tango":
  {
   "time_signature": 0,
     "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"valse_viennoise":
  {
    "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.3, //hymne à l'amour 
    "sc_range": 0.1, 
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"Slow fox":
  {
    "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
    
},
"Quickstep":
  {
    "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
    
},
"Cha-cha-cha":
  {
   "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
    
},
"Rumba":
  {
    "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"Samba":
  {
    "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"Paso doble":
  {
   "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},

"Jive":
  {
   "time_signature": 0,
    "accent_profile": 0.1,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"Salsa":
  {
   "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
},
"Rock 4 temps":
  {
   "time_signature": 0,
 "accent_profile": 0.1,
    "accent_profile": 0.1,
    "accent_profile_array": 0.1,
    "bdr_mean": 0.1,
    "bdr_range": 0.1,
    "bpm_histogram": 0.1,
    "bpm_mean": 0.1, 
    "bpm_range": 0.1,
    "danceability_mean": 0.1,
    "danceability_range": 0.1,
    "energy_mean": 0.1,
    "energy_range": 0.1,
    "flatness_mean": 0.1,
    "flatness_range": 0.1,
    "ibi_mean": 0.1,
    "ibi_range": 0.1,
    "ibis_hist": 0.1,
    "ibis_norm": 0.1, 
    "mfcc_profile": 0.1,
    "onset_rate_mean": 0.1, 
    "onset_rate_range": 0.1,
    "rp_2": 0.1,
    "rp_3": 0.1,
    "rp_6": 0.1,
    "rp_12": 0.1,
    "sc_mean": 0.1, 
    "sc_range": 0.1,
    "swing_ratio_mean": 0.1,
    "swing_ratio_range": 0.1,
    "zcr_mean": 0.1,
    "zcr_range": 0.1,
    
  }
}
